### ISSUE TITLE
Standard Fonts

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/thegrandmacon#11]
On any Event, please make category and more info the same font 
https://cloudup.com/cUykiMDotqE

Ex: http://thegrandmacon.wpengine.com/all-events/live-and-let-die-paul-mccartney/

**Comment by Sporkyy** [comment]
@elcopeland Which font? Serif or Sans?

**Comment by cinakur** [comment]
Serif (TT Old Standard), por favor

**Comment by Sporkyy** [comment]
Gotcha. Closed in 7fe2f75
