### ISSUE TITLE
Add new class for Title + line Styling on dark background

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/thegrandmacon#13]
Created a new class

`.add-line--dark`

Could you please add this (or something similar) to styles.css, where it is white and there's a bottom margin?

**Comment by cinakur** [comment]
Or maybe it needs to also have a line, after it. 

.... Yeah, can you please also add a 5 px thick #EBAE36 line after it? 

color: #fff;
padding-bottom: 1em;

::after
5x solid #EBAE36 
33% wide

**Comment by Sporkyy** [comment]
It's a class on the row `.row--charcoal`

**Comment by Sporkyy** [comment]
Closed by a399f4e
