### ISSUE TITLE
style the MEC more info link as a button

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/thegrandmacon#14]
Current: 

![image](https://user-images.githubusercontent.com/22402707/42330590-7c30cab4-8041-11e8-8114-028043b3b6a0.png)

Requested: 

![image](https://user-images.githubusercontent.com/22402707/42330602-8383041c-8041-11e8-8a3f-f97dbfb59e2c.png)

**Comment by cinakur** [comment]
//per our conversation, use substring selectors so that when user enters a link that includes purchase.tickets.com/buy/TicketPurchase, it automatically styles to button.

**Comment by Sporkyy** [comment]
Is this screenshot from a time when a different Single Event Style was selected? I don't see how to get text over into the left column like that.

**Comment by cinakur** [comment]
same style! it's controlled through the "More Info" field on the edit page. 

(at bottom of screen shot:) 

![image](https://user-images.githubusercontent.com/22402707/42471252-0a63a9a4-838b-11e8-9141-7d87cefd2fed.png)
