### ISSUE TITLE
Change Event Filter Styling

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/thegrandmacon#20]
https://cloudup.com/ceT3dW5oboL

http://thegrandmacon.wpengine.com/events/

**Comment by Sporkyy** [comment]
"Charcoal is the highlight color." she says.

**Comment by Sporkyy** [comment]
I made the selected+hover color GOH Goldenrod, otherwise the text would disappear,

**Comment by Sporkyy** [comment]
Closed by da66c70
