### ISSUE TITLE
There are four images that are loading as http instead of https

### ISSUE THREAD

**Issue by robsaxon** [merceruniversity/thegrandmacon#24]
Mixed Content: The page at 'https://www.thegrandmacon.com/' was loaded over HTTPS, but requested an insecure image 'http://thegrandmacon.wpengine.com/wp-content/uploads/2018/07/wendy-finding-neverland.jpg?id=212'. This content should also be served over HTTPS.
(index):1 Mixed Content: The page at 'https://www.thegrandmacon.com/' was loaded over HTTPS, but requested an insecure image 'http://thegrandmacon.wpengine.com/wp-content/uploads/2018/07/goh-seats-01-300x200.jpg'. This content should also be served over HTTPS.
(index):1 Mixed Content: The page at 'https://www.thegrandmacon.com/' was loaded over HTTPS, but requested an insecure image 'http://thegrandmacon.wpengine.com/wp-content/uploads/2018/07/DSC00030-2-300x200.jpg'. This content should also be served over HTTPS.
(index):1 Mixed Content: The page at 'https://www.thegrandmacon.com/' was loaded over HTTPS, but requested an insecure image 'http://thegrandmacon.wpengine.com/wp-content/uploads/2018/07/chandelier-01-300x200.jpg'. This content should also be served over HTTPS.

**Comment by Sporkyy** [comment]
They're also using the wrong domain `thegrandmacon.wpengine.com` instead of `'www.thegrandmacon.com`. All fixed last week.
