### ISSUE TITLE
/contribute Fix skewed-background 

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/thegrandmacon#6]

**Comment by Sporkyy** [comment]
Still thinking this part through there needs to be three classes to achieve success on this page.

- `.goh-column-box`
- `.goh-column-box--skewed`
- `.goh-column-box--centered`

The default for the skewed backgrounds will be changed to not overflow the column by default. The GOH homepage will need to be configured with a class such as `goh-column-box--overflowing` class, and then, of course have that class be created in CSS with the appropriate attributes.

**Comment by Sporkyy** [comment]
Works well now with added padding added between the inner rows in the page builder.
