### ISSUE TITLE
Identify Standard Button + Hover behavior

### ISSUE THREAD

**Issue by cinakur** [merceruniversity/thegrandmacon#8]

**Comment by Sporkyy** [comment]
I'll change the button CSS classes to use the `goh-*` prefix so there are now classes like

- `.goh-btn`
- `.goh-btn--primary`
- `.goh-btn--secondary`
- `.goh-btn--tertiary`

**Comment by Sporkyy** [comment]
This works fairly well now and the styles are based on the designs in Figma.

There are some overrides i the child theme CSS in the "Shame" section where the theme CSS needed to be manhandled with some ID selectors.
